apiVersion: v1
kind: ServiceAccount
metadata:
  name: topo-aware-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: noderesourcetoplogy-handler
rules:
- apiGroups: ["topology.node.k8s.io"]
  resources: ["noderesourcetopologies"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch","update"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: topo-aware-scheduler-as-kube-scheduler
subjects:
  - kind: ServiceAccount
    name: topo-aware-scheduler
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: noderesourcetoplogy-handler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: topo-aware-scheduler-as-kube-scheduler
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: topo-aware-scheduler
    namespace: kube-system
roleRef:
  kind: Role
  name: extension-apiserver-authentication-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
    tier: control-plane
  name: topo-aware-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        component: scheduler
        tier: control-plane
        version: second
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      serviceAccountName: topo-aware-scheduler
      containers:
        - image: quay.io/swsehgal/scheduler-plugins-kube-scheduler:latest
          # command:
          # - /bin/kube-scheduler
          # - --scheduler-name=topo-aware-scheduler
          # - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
          # - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
          # - --config=/etc/kubernetes/scheduler-config/scheduler-config.yaml
          args:
          - sleep
          - "10000000"
          name: scheduler
          securityContext:
            privileged: false
          volumeMounts:
          - mountPath: /etc/kubernetes/scheduler.conf
            name: kubeconfig
          - mountPath: /etc/kubernetes/scheduler-config
            name: topo-aware-scheduler-config-vol
      hostNetwork: false
      hostPID: false
      volumes:
      - hostPath:
          path: /etc/kubernetes/scheduler.conf
          type: File
        name: kubeconfig
      - configMap:
          name: topo-aware-scheduler-config
        name: topo-aware-scheduler-config-vol
