apiVersion: topology.node.k8s.io/v1alpha1
kind: NodeResourceTopology
metadata:
  name: kind-worker
topologyPolicy: "SingleNUMANode"
zones:
  node-0:
    type: Node
    resources:
      cpu:
        capacity: "4"
        allocatable: "3"
      example.com/deviceA:
        capacity: "3"
        allocatable: "3"
  node-1:
    type: Node
    resources:
      cpu:
        capacity: "4"
        allocatable: "3"
      example.com/deviceB:
        capacity: "3"
        allocatable: "3"
